export const ActionTypes = {
	
	/* Async Actions */
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	FETCH_ACCOUNTS_REQUEST: 'FETCH_ACCOUNTS_REQUEST',
	FETCH_ACCOUNTS_SUCCESS: 'FETCH_ACCOUNTS_SUCCESS',
	FETCH_ACCOUNTS_FAILURE: 'FETCH_ACCOUNTS_FAILURE',

	/* User Actions */
	SUBMIT_LOGIN_FORM: 'SUBMIT_LOGIN_FORM'
	SELECT_ACCOUNT: 'SELECT_ACCOUNT'
};